baseURL: "https://validatedpatterns.io/"
languageCode: "en-us"
title: Validated Patterns
theme: "patternfly"
summaryLength: 20
paginate: 6
params:
  site_logo: /images/validated-patterns.png
security:
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv: (?i)^(GEM_PATH|PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$
  funcs:
    getenv:
    - ^HUGO_

markup:
  asciidocExt:
    attributes: {allow-uri-read, source-highlighter: rouge, icons: font, sectanchors, showtitle}
    safeMode: unsafe
    imagesdir: images
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  industry: 'industries'
  product: 'products'
  blog_tag: 'blog_tags'

module:
  mounts:
  - source: archetypes
    target: archetypes
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: modules
    target: content